backend:
  name: git-gateway
  branch: main

media_folder: "smiling-axolotl/public/images/projects"
public_folder: "/images/projects"

collections:
  - name: "projects"
    label: "Projects"
    folder: "smiling-axolotl/src/data/projects"
    format: "json"
    extension: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, min: 1, max: 3, options: ["OWNERSHIP", "PARTNERSHIP", "THIRD-PARTY", "GAME-JAM"], required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Link", name: "url", widget: "string", required: false, pattern: ['^https?://.*', 'Must be a valid URL starting with http:// or https://']}
      - {label: "Display on Website", name: "display", widget: "boolean", default: true, required: true, hint: "Toggle to show/hide this project on the website"}